version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: apt-get install wiringpi
      - run:
          name: Compile
          command: make

